### PR TITLE
Added Swift 4 - Xcode 9 support

### PR DESCRIPTION
**Pull request by mohpor**

### CODE REVIEW

**Comment by WenchaoD** [comment]
Can you submit a **source-only**  pull request?

**Comment by mohpor** [comment]
I don’t know what source-only means!
This is a version migration, of course there’s going to be some changes in project files too.

**Comment by sumeshd** [comment]
How do I pull the code into from my pod file? 
I tried this but didn't work: 
pod 'FSPagerView', :git => 'https://github.com/WenchaoD/FSPagerView.git', :commit => '5b5710f517a2372d2fa68e2a205d44076ecabf1c'

The error I get is this: 
[!] Error installing FSPagerView
[!] Failed to download 'FSPagerView'.

**Comment by WenchaoD** [comment]
Fixed, thanks.

**Pull request closed without merging**
